use super::easy::*;
use super::hard::*;
use super::medium::*;
use enum_dispatch::enum_dispatch;
#[enum_dispatch(Solver)]
pub(crate) enum SolverEnum {
    NakedSingle,
    HiddenSingle,
    Pointing,
    Claiming,
    NakedPair,
    HiddenPair,
    NakedTriple,
    HiddenTriple,
    XWing,
    Swordfish,
    Skyscraper,
    TwoStringKite,
    TurbotFish,
    EmptyRectangle,
    BiValueUniversalGravePlusOne,
    UniquenessTest1,
    UniquenessTest2,
    UniquenessTest3,
    UniquenessTest4,
    UniquenessTest5,
    UniquenessTest6,
    FinnedXWing,
    AvoidableRectangle1,
    AvoidableRectangle2,
    NakedQuadruple,
    HiddenQuadruple,
    Jellyfish,
    XYWing,
    XYZWing,
    WWing,
    FinnedSwordfish,
    FinnedJellyfish,
    Coloring,
    SueDeCoq,
}
